### ISSUE TITLE
支持Django ninja吗？

### ISSUE THREAD

**Issue by tahitimoon** [utilmeta/utilmeta-py#1]
支持[Django ninja](https://django-ninja.dev/)吗？粗略看了一下文档，感觉非常不错，打算用这个把自己的项目改造一下

**Comment by voidZXL** [comment]
Django Ninja 是 Django 的一个 REST wrapper，所以如果你是现有的 Django Ninja  项目接入单个 UtilMeta 接口的话，可以像普通 [Django 项目的集成](https://docs.utilmeta.com/py/zh/guide/migration/#django) 一样直接使用 `urlpatterns` 定义，比如

```python
from django.urls import path
from ninja import NinjaAPI
from utilmeta.core import api

class RootAPI(api.API):
    @api.get
    def add(self, a: int, b: int) -> int:
        return a + b

api = NinjaAPI()

urlpatterns = [
    path("v1/", api.urls),
    RootAPI.__as__(django, route='/api'),
]
```

如果你准备使用一个新的 UtilMeta 项目集成现有的 Django Ninja 接口，可以使用服务的 `mount` 方法，参考这里的实现 https://docs.utilmeta.com/py/zh/guide/migration/#django-ninja

```python
import django
from utilmeta import UtilMeta

service = UtilMeta(__name__, backend=django, name='demo')

from utilmeta.core.server.backends.django import DjangoSettings
service.use(DjangoSettings())
service.setup()

from ninja import NinjaAPI
ninja_api = NinjaAPI()

@ninja_api.get("/add")
def add(request, a: int, b: int):
    return {"result": a + b}

service.mount(ninja_api, '/v1')

app = service.application()
```

同理适用于其他基于 Django 的框架，比如 [DRF](https://docs.utilmeta.com/py/zh/guide/migration/#drf)
