### ISSUE TITLE
[problem] create app user failed when start a new project

### ISSUE THREAD

**Issue by Cherrymelon** [utilmeta/utilmeta-py#3]
I'm following doc to create the Realworld project,I use django as backend.
1. run `pip install utilmeta django`
2. run `meta setup myproject`
3. run `meta create user`

but it failed and tell me secret_key not set, I think it will be auto generate.However, it still failed when rerun

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/5cfcdd57-3e5e-4129-8647-579c968be0a2">

**Comment by voidZXL** [comment]
👋 You can also join our discord server: https://discord.gg/JdmEkFS6dS to discuss problems like this, perhaps our document is not clear enough and you could help us out
