### ISSUE TITLE
[doc]more explaination detail about http_only field 

### ISSUE THREAD

**Issue by Cherrymelon** [utilmeta/utilmeta-py#5]
What situation ti should be true or false?

**Comment by voidZXL** [comment]
If the `http_only` param you referred to is from https://docs.utilmeta.com/py/en/guide/auth/#configure-cookie section,
the explanation in the document is clear:
> `http_only`: if set to True, the cookie will not be accessed or modified by the client’s JavaScript and will only be passed in the HTTP request. For the session cookie, it is recommended to set to True for security.

If you used the cookie in Session or other authentication methods, it is recommended to set to `True`, as this cookie will only be sent in the HTTP requests, and cannot be accessed (thus, leaked) by the client's script

The detailed explanation can also be found in [Block access to your cookies | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#block_access_to_your_cookies)

**Comment by Cherrymelon** [comment]
额，对比了一下，中文版本没有对应解释，英文版本才是最完整的？？？

**Comment by voidZXL** [comment]
中文版也有的：https://docs.utilmeta.com/py/zh/guide/auth/#cookie

**Comment by Cherrymelon** [comment]
在顶部的搜索栏里搜http_only只能搜到代码字段，http_only字段定义部分在搜索结果里没有。
<img width="636" alt="image" src="https://github.com/user-attachments/assets/ac57b8e0-3fd0-45fc-bb51-4eb7ab4f0256">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/8809e33c-4962-4fa9-b2f0-e271591ae1b7">

**Comment by voidZXL** [comment]
那可能是 Material for Mkdocs 对中文文档的搜索优化的不够好，框架文档是直接用的 [搜索插件](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search)
https://github.com/utilmeta/utilmeta-py/blob/main/docs/mkdocs.zh.yml#L38

我的微信 ID 也是 voidZXL，UtilMeta 框架有微信群进行中文讨论，可以加我拉群
